vim.keymap.set('n', '<C-a>', 'gg<S-v>G')
vim.keymap.set('n', 'sp', ':split<Return><C-w>w')
vim.keymap.set('n', 'sv', ':vsplit<Return><C-w>w')
vim.keymap.set('', 'sh', '<C-w>h')
vim.keymap.set('', 'sj', '<C-w>j')
vim.keymap.set('', 'sk', '<C-w>k')
vim.keymap.set('', 'sl', '<C-w>l')
vim.keymap.set('n', 'te', ':tabedit<CR>')
